# Generated by Django 5.2.8 on 2025-12-15 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstyletag',
            name='style_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.styletag'),
        ),
        migrations.AddField(
            model_name='userstyletag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='style_tags',
            field=models.ManyToManyField(blank=True, related_name='users', through='accounts.UserStyleTag', to='myapp.styletag'),
        ),
        migrations.AlterUniqueTogether(
            name='userstyletag',
            unique_together={('user', 'style_tag')},
        ),
    ]
