# Generated by Django 5.2.8 on 2025-12-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='temp_uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
