# Generated by Django 5.2.8 on 2025-12-24 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_image_url', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('product_description', models.TextField()),
                ('target_pet_type', models.CharField(blank=True, choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=10, null=True)),
                ('min_follower_count', models.IntegerField(default=0)),
                ('requested_at', models.DateTimeField()),
                ('application_deadline_at', models.DateField()),
                ('posting_start_at', models.DateField()),
                ('posting_end_at', models.DateField()),
                ('required_creator_count', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('style_tags', models.ManyToManyField(blank=True, related_name='campaigns', to='myapp.styletag')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignAcceptance',
            fields=[
                ('campaign_acceptance_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_decision_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('brand_decided_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='myapp.campaign')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('campaign', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('deliverable_id', models.AutoField(primary_key=True, serialize=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('post_url', models.CharField(blank=True, max_length=255, null=True)),
                ('deliverable_status', models.CharField(choices=[('incomplete', 'Incomplete'), ('completed', 'Completed')], default='incomplete', max_length=10)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='deliverables/')),
                ('ai_validation_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ai_result_raw', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_acceptance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable', to='myapp.campaignacceptance')),
            ],
        ),
        migrations.CreateModel(
            name='DeliverableRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('object', 'Object'), ('scene', 'Scene'), ('action', 'Action'), ('text', 'Text')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='myapp.campaign')),
            ],
        ),
    ]
