# Generated by Django 5.2.8 on 2025-12-19 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='ai_validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='content',
            field=models.TextField(default='content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverable',
            name='image',
            field=models.ImageField(default='deliverables/deliverable_test.jpg', upload_to='deliverables/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverable',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='campaign_acceptance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverable', to='myapp.campaignacceptance'),
        ),
        migrations.CreateModel(
            name='DeliverableRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('object', 'Object'), ('scene', 'Scene'), ('action', 'Action'), ('text', 'Text')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='myapp.campaign')),
            ],
        ),
    ]
