# Generated by Django 5.2.8 on 2025-12-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_deliverable_ai_result_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='product_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deliverables/'),
        ),
    ]
