# Generated by Django 5.2.8 on 2025-12-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_campaign_product_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='product_image_url',
            new_name='product_image',
        ),
    ]
