# Generated by Django 5.2.8 on 2025-12-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_product_image_url_campaign_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='product_image',
            new_name='product_image_url',
        ),
    ]
