"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
import environ

from dotenv import load_dotenv
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--o&bfrkfby5z$*e3ktoh90j1+_9$_fl1ihz=v_yxlap0mojhux'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'ai',
    'accounts',
    'myapp',
    "corsheaders",
    'rest_framework',
    'storages',
    'sslserver',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

CORS_ALLOWED_ORIGINS = [
    "https://localhost:5173",
]
CORS_ALLOW_CREDENTIALS = True


SIMPLE_JWT = {
    # Access Token 유효 시간
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),

    # Refresh Token 유효 시간
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    # 선택 (보안 강화용, 지금은 굳이 안 해도 됨)
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
}

'''
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'media/'


# GCS 설정
GS_BUCKET_NAME = 'pawfecto-storage-admin' 
GS_PROJECT_ID = 'pawfecto' 
GS_FILE_OVERWRITE = True

# 1. 경로 설정: Path 객체를 사용하여 절대 경로 확보 후 슬래시(/) 변환
GOOGLE_APPLICATION_CREDENTIALS_PATH = (BASE_DIR / 'keys' / 'service-account-key.json').as_posix()

# 2. 환경 변수 등록: os.environ에 직접 박아야 라이브러리가 즉시 인식함
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = GOOGLE_APPLICATION_CREDENTIALS_PATH

# 3. 라이브러리용 변수 설정
GOOGLE_APPLICATION_CREDENTIALS = GOOGLE_APPLICATION_CREDENTIALS_PATH

# 4. 저장 엔진 설정
DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'

# 5. [추가] 수동으로 세션을 유지하지 않도록 설정 (권한 에러 방지)
GS_DEFAULT_ACL = None  # 버킷의 기본 권한 설정을 따름
'''

# ==============================================================================
# MEDIA & GCS STORAGE SETTINGS
# ==============================================================================

# 1. 로컬 미디어 설정 제거 (로컬 저장을 방지하기 위해 반드시 주석 처리하거나 삭제하세요)
# MEDIA_ROOT = BASE_DIR / 'media'
# MEDIA_URL = '/media/'

# 2. GCS 기본 정보 설정
GS_BUCKET_NAME = 'pawfecto'  # 스크린샷에서 확인된 실제 버킷 이름으로 수정
GS_PROJECT_ID = 'pawfecto' 
GS_FILE_OVERWRITE = True
GS_DEFAULT_ACL = None  # 버킷의 '공개 액세스 방지' 설정을 따르거나 allUsers 권한을 따름

# 3. GCS 인증 설정 (윈도우 경로 호환성 확보)
import os
from pathlib import Path

# 키 파일의 절대 경로를 슬래시(/) 방향으로 생성
GOOGLE_APPLICATION_CREDENTIALS_PATH = (BASE_DIR / 'keys' / 'service-account-key.json').as_posix()

# 시스템 환경 변수에 즉시 등록 (라이브러리 인식 필수 단계)
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = GOOGLE_APPLICATION_CREDENTIALS_PATH
GOOGLE_APPLICATION_CREDENTIALS = GOOGLE_APPLICATION_CREDENTIALS_PATH

# 4. 파일 저장 엔진 설정 (이 줄이 로컬 대신 GCS를 사용하게 만드는 핵심입니다)
# DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}



# ==============================================================================
# API keys and settings for AI services
GMS_API_KEY = os.getenv("GMS_API_KEY")
GMS_OPENAI_BASE_URL = os.getenv("GMS_OPENAI_BASE_URL")

AI_MODEL_PRIMARY = os.getenv("AI_MODEL_PRIMARY", "gpt-4.1")
AI_MODEL_CHEAP = os.getenv("AI_MODEL_CHEAP", "gpt-4.1-mini")


# Django가 이 출처(origin)를 신뢰하지 않아서 POST 요청을 차단 방지
CSRF_TRUSTED_ORIGINS = [
    "https://localhost:5173",
    "https://127.0.0.1:5173",
]

env = environ.Env()
# 환경 변수 파일을 로드
environ.Env.read_env()

# 환경 변수 사용
INSTAGRAM_CLIENT_ID = env('INSTAGRAM_CLIENT_ID')
INSTAGRAM_CLIENT_SECRET = env('INSTAGRAM_CLIENT_SECRET')

# settings.py 맨 아래에 추가

# 1. 모든 쿠키를 보안 모드(HTTPS)로만 전송하도록 강제
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# 2. 크로스 도메인(5173 -> 8000) 간의 쿠키 공유를 위해 SameSite를 'None'으로 설정
SESSION_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SAMESITE = 'None'

# 3. CORS 설정 확인 (프론트엔드 주소 허용)
CORS_ALLOW_CREDENTIALS = True  # 쿠키를 실어 보내기 위해 필수
CORS_ALLOWED_ORIGINS = [
    "https://localhost:5173",
    "https://127.0.0.1:5173",
]
