############################################
### 0-1. 로그인 (크리에이터: puppy_daily, pk = 6)
############################################
POST https://127.0.0.1:8000/accounts/login/
Content-Type: application/json

{
  "username": "Alice",
  "password": "test1234"
}


### 로그인 응답에서 token을 복사해 아래 변수에 넣어라
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2NDI1MzU2LCJpYXQiOjE3NjY0MTgxNTYsImp0aSI6IjYwNTE1OWU2MTExYjQxMWZhYTlkOTY3M2NhNDJkMmIyIiwidXNlcl9pZCI6IjIzIn0.n3ASLVActhZdzmDAf0NxM-ixGq3yyaehuI-48S6kPOo
############################################
### 1. Deliverable 제출 (캡션 + 이미지 업로드)
### campaign_acceptance_id = 21 예시
### POST /api/v1/campaign-acceptances/{campaign_acceptance_id}/deliverable/
############################################
POST https://127.0.0.1:8000/api/v1/campaign-acceptances/21/deliverable/
Authorization: Bearer {{token}}
Content-Type: multipart/form-data

content=급여 후 반려견의 반응이 매우 좋았습니다. #협찬 #네추라펫
image=@./test_image.jpg



############################################
### 2. Deliverable AI 검증 요청
### deliverable_id = 10
### POST /api/v1/deliverables/{deliverable_id}/verify/
############################################
POST https://127.0.0.1:8000/api/v1/deliverables/10/verify/
Authorization: Bearer {{token}}
Content-Type: application/json

###
POST https://127.0.0.1:8000/api/v1/deliverables/1/verify/
Authorization: Bearer {{token}}
Content-Type: application/json

{}


###
POST https://127.0.0.1:8000//api/v1/deliverables/1/
Content-Type: multipart/form-data

############################################
### 3. 크리에이터 진행 상황 조회 (상태 확인)
### creator_id = 6
### GET /api/v1/creator/{creator_id}/progress/
############################################
GET https://127.0.0.1:8000/api/v1/creator/6/progress/
Authorization: Bearer {{token}}
