############################################
### 0-1. 로그인 (크리에이터: puppy_daily, pk = 6)
############################################
POST http://127.0.0.1:8000/accounts/login/
Content-Type: application/json

{
  "username": "puppy_daily",
  "password": "test1234"
}


### 로그인 응답에서 token을 복사해 아래 변수에 넣어라
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY2MTc2OTk0LCJpYXQiOjE3NjYxNjk3OTQsImp0aSI6IjlmMGU0NDZhM2NiNDRmNDRiOWFkZTQ0N2E4ZTc4M2JjIiwidXNlcl9pZCI6IjYifQ.Jb7aSsIjGochGyb_7915VhNt1Xkr7A8lF3HSVDq4PNI



############################################
### 1. Deliverable 제출 (캡션 + 이미지 업로드)
### campaign_acceptance_id = 21 예시
### POST /api/v1/campaign-acceptances/{campaign_acceptance_id}/deliverable/
############################################
POST http://127.0.0.1:8000/api/v1/campaign-acceptances/21/deliverable/
Authorization: Bearer {{token}}
Content-Type: multipart/form-data

content=급여 후 반려견의 반응이 매우 좋았습니다. #협찬 #네추라펫
image=@./test_image.jpg



############################################
### 2. Deliverable AI 검증 요청
### deliverable_id = 10
### POST /api/v1/deliverables/{deliverable_id}/verify/
############################################
POST http://127.0.0.1:8000/api/v1/deliverables/10/verify/
Authorization: Bearer {{token}}
Content-Type: application/json



############################################
### 3. 크리에이터 진행 상황 조회 (상태 확인)
### creator_id = 6
### GET /api/v1/creator/{creator_id}/progress/
############################################
GET http://127.0.0.1:8000/api/v1/creator/6/progress/
Authorization: Bearer {{token}}
